# Generated by Django 6.1.1 on 2026-09-24 11:17

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_favorite_type'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='favorite',
            name='unique_user_movie_favorite',
        ),
        migrations.RenameField(
            model_name='favorite',
            old_name='type',
            new_name='media_type',
        ),
        migrations.RenameField(
            model_name='favorite',
            old_name='movie_id',
            new_name='tmdb_id',
        ),
        migrations.AddConstraint(
            model_name='favorite',
            constraint=models.UniqueConstraint(fields=('user', 'tmdb_id', 'media_type'), name='unique_user_tmdb_favorite'),
        ),
    ]
